include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - records

linter:
  rules:
    directives_ordering: true
    non_constant_identifier_names: false
    curly_braces_in_flow_control_structures: false
    avoid_dynamic_calls: false
    avoid_relative_lib_imports: true
    avoid_unused_constructor_parameters: true
    prefer_const_constructors: false
    prefer_relative_imports: true
    prefer_const_literals_to_create_immutables: false
    prefer_single_quotes: true
    sort_unnamed_constructors_first: true
    no_leading_underscores_for_local_identifiers: false
