name: browser_data
description: dart package to retrieve browser's data.
version: 0.0.3
repository: https://github.com/thitlwincoder/browser_data
issue_tracker: https://github.com/thitlwincoder/browser_data/issues

environment:
  sdk: ^3.0.6

funding:
  - https://paypal.me/thitlwin312
  - https://ko-fi.com/thitlwincoder

topics:
  - browser
  - data

platforms:
  linux:
  macos:
  windows:

dependencies:
  file_copy: ^1.0.7

  path: ^1.8.3
  logger: ^2.0.2+1

  sqlite3: ^2.1.0
  win32_registry: ^1.1.2

dev_dependencies:
  lints: ^2.1.1
