name: browser_data
description: dart package to retrieve browser's data.
version: 0.0.4
repository: https://github.com/thitlwincoder/browser_data
issue_tracker: https://github.com/thitlwincoder/browser_data/issues

environment:
  sdk: ^3.0.6

funding:
  - https://paypal.me/thitlwin312
  - https://ko-fi.com/thitlwincoder

topics:
  - browser
  - data

platforms:
  linux:
  macos:
  windows:

dependencies:
  file_copy: ^1.0.7

  path: ^1.9.0
  logger: ^2.3.0

  sqlite3: ^2.4.3
  win32_registry: ^1.1.3

  win32: ^5.5.0
  ffi: ^2.1.2
  encrypt: ^5.0.3

dev_dependencies:
  lint: ^2.3.0
