name: browser_data
description: dart package to retrieve browser's data.
version: 0.0.5
repository: https://github.com/thitlwincoder/browser_data
issue_tracker: https://github.com/thitlwincoder/browser_data/issues

environment:
  sdk: ^3.5.4

funding:
  - https://paypal.me/thitlwin312
  - https://ko-fi.com/thitlwincoder

topics:
  - browser
  - data

platforms:
  linux:
  macos:
  windows:

dependencies:
  path: ^1.9.1
  logger: ^2.5.0

  sqlite3: ^2.7.5
  win32_registry: ^2.1.0

  win32: ^5.12.0
  ffi: ^2.1.4
  encrypt: ^5.0.3

dev_dependencies:
  lints: ^5.1.1
